### ISSUE TITLE
Upgrading to kernel 5.3.8.1 removes battery indicator and power reporting

### ISSUE THREAD

**Issue by woberts** [StollD/linux-fedora#1]
Sorry if this is the wrong place to report it but after upgrading to 5.3.8.1 on Fedora (30 or 31) the battery indicator has gone and battery status is no longer reported via Settings -> Power or Power Statistics. Attached dmesg.txt in case it helps.

[dmesg.txt](https://github.com/StollD/linux-fedora/files/3791111/dmesg.txt)

**Comment by StollD** [comment]
Ah, damm. qzed renamed the SURFACE_ACPI module to SURFACE_SAM, and I totally missed that those changes were already in the patches and forgot to update the config accordingly. I'll make a new build as soon as possible. Thanks for the report.

Also, better open such issues on https://github.com/StollD/fedora-linux-surface. This repo is just an automated mirror of Fedoras default kernel, totally unrelated to surface.

**Comment by woberts** [comment]
No worries, I’ll try to remember where to report In future. Thanks for all your efforts.

**Comment by StollD** [comment]
Actually it seems as if qzed only updated the patch for 4.19, not the one for 5.3. But i might have managed to mix in some development patches into my local build environment. Anyways, a clean build, which should fix all of that, is on the way.

EDIT: scratch that, the updated surface_acpi is part of the IPTS patch for some reason.

**Comment by StollD** [comment]
`5.3.8-2` should be rolling out on both, F30, and F31 now, fixing the `surface_acpi` / `surface_sam` module.

Closing this.
